import { describe, expect, it } from "vitest";
import JSZip from "jszip";
import { buildBambu3mf, fixture, TINY_PNG } from "../../../tests/fixtures/bambu/build";
import { defaultUnitsOnPlate, matchMaterial, parseProjectSettings, parseSliceInfo, plateGrams, plateObjectGroups, primaryFilament, readBambu3mf, suggestFromPlate } from "./bambu-3mf";

const CURRENT = fixture("current-two-plates.slice_info.config");
const V104 = fixture("v01.04-single-plate.slice_info.config");
const UNSLICED = fixture("unsliced-project.slice_info.config");
const NO_WEIGHT = fixture("no-weight.slice_info.config");
const PROJECT = fixture("project_settings.config");

describe("parseSliceInfo — current Bambu Studio format", () => {
  const info = parseSliceInfo(CURRENT);

  it("reads the header and every sliced plate", () => {
    expect(info.clientType).toBe("slicer");
    expect(info.clientVersion).toBe("02.02.01.60");
    expect(info.plates.map((p) => p.index)).toEqual([1, 2]);
  });

  it("reads time in seconds, weight in grams and plate flags", () => {
    const [p1] = info.plates;
    expect(p1.printSeconds).toBe(7384);
    expect(p1.weightG).toBe("58.42");
    expect(p1.supportUsed).toBe(true);
    expect(p1.printerModelId).toBe("C12");
    expect(p1.nozzleDiameters).toBe("0.4");
  });

  it("reads filaments sorted by slot, normalising 8-digit colours", () => {
    const p2 = info.plates[1];
    expect(p2.filaments.map((f) => [f.slot, f.type, f.color, f.usedG, f.trayInfoIdx])).toEqual([
      [1, "PLA", "#000000", "25.65", "GFA01"],
      [2, "PLA", "#FFFFFF", "6.25", "GFA00"],
    ]);
    expect(p2.filaments[0].usedForSupport).toBe(false);
  });

  it("decodes XML entities and non-Latin names, and keeps skipped flags", () => {
    const p2 = info.plates[1];
    expect(p2.objects[0].name).toBe("Box & lid — קופסה");
    expect(p2.objects.filter((o) => o.skipped)).toHaveLength(1);
  });

  it("reads warnings despite the slicer's `error_code =` spacing", () => {
    expect(info.plates[1].warnings).toEqual([
      {
        message: "bed_temperature_too_high_than_filament",
        level: "1",
        code: "1000C001",
      },
    ]);
  });
});

describe("parseSliceInfo — other versions and edge cases", () => {
  it("reads the v01.04 format (no objects, no tray ids, no printer model)", () => {
    const info = parseSliceInfo(V104);
    expect(info.clientVersion).toBe("01.04.00.17");
    const [p] = info.plates;
    expect(p).toMatchObject({
      index: 1,
      printSeconds: 2710,
      weightG: "12.08",
      supportUsed: false,
      printerModelId: null,
      objects: [],
    });
    expect(p.filaments).toEqual([
      {
        slot: 1,
        type: "PETG",
        color: "#F72323",
        usedG: "12.08",
        usedM: "3.95",
        trayInfoIdx: null,
        usedForSupport: null,
      },
    ]);
  });

  it("returns no plates for an unsliced project", () => {
    expect(parseSliceInfo(UNSLICED).plates).toEqual([]);
  });

  it("treats empty weight and zero prediction as missing, never as zero", () => {
    const [p] = parseSliceInfo(NO_WEIGHT).plates;
    expect(p.index).toBe(3);
    expect(p.weightG).toBeNull();
    expect(p.printSeconds).toBeNull();
    expect(plateGrams(p)).toBe("4.65");
  });

  it("rejects malformed XML and foreign documents", () => {
    expect(() => parseSliceInfo("<config><plate>")).toThrow();
    expect(() => parseSliceInfo("<svg></svg>")).toThrow();
  });

  it("ignores non-numeric values instead of guessing", () => {
    const info = parseSliceInfo(
      `<config><plate><metadata key="index" value="x"/><metadata key="prediction" value="1e9"/><metadata key="weight" value="-3"/><filament id="1" type="PLA" color="red" used_g="abc"/></plate></config>`,
    );
    const [p] = info.plates;
    expect(p).toMatchObject({ index: 1, printSeconds: null, weightG: null });
    expect(p.filaments[0]).toMatchObject({ color: null, usedG: null });
  });
});

describe("parseProjectSettings", () => {
  it("reads printer, presets and layer height from JSON", () => {
    expect(parseProjectSettings(PROJECT)).toEqual({
      version: "02.02.01.60",
      printerModel: "Bambu Lab P1S",
      printerPreset: "Bambu Lab P1S 0.4 nozzle",
      processPreset: "0.20mm Standard @BBL X1C",
      layerHeight: "0.2",
      filamentPresets: ["Bambu PLA Basic @BBL X1C", "Bambu PLA Basic @BBL X1C"],
    });
  });
  it("returns null for non-JSON (older INI-style) content", () => {
    expect(parseProjectSettings("; generated by BambuStudio\nlayer_height = 0.2")).toBeNull();
    expect(parseProjectSettings("[1,2]")).toBeNull();
  });
});

describe("plate helpers", () => {
  const [p1, p2] = parseSliceInfo(CURRENT).plates;

  it("groups printable objects and proposes units per plate", () => {
    expect(plateObjectGroups(p1)).toEqual([{ name: "Bracket", count: 4 }]);
    expect(defaultUnitsOnPlate(p1)).toBe(4);
    // Different parts on one plate = probably one assembly; skipped objects don't count.
    expect(plateObjectGroups(p2)).toEqual([
      { name: "Box & lid — קופסה", count: 1 },
      { name: "Lid", count: 1 },
    ]);
    expect(defaultUnitsOnPlate(p2)).toBe(1);
    expect(defaultUnitsOnPlate(parseSliceInfo(V104).plates[0])).toBe(1);
  });

  it("picks the heaviest filament as primary", () => {
    expect(primaryFilament(p2)?.slot).toBe(1);
  });

  it("splits plate weight and time per unit, rounding up", () => {
    expect(suggestFromPlate(p1, 4)).toEqual({
      ok: true,
      gramsPerUnit: "14.61",
      printMinutesPerUnit: 31,
      unitsPerBatch: 4,
      plateGrams: "58.42",
      plateSeconds: 7384,
    });
    expect(suggestFromPlate(p1, 1)).toMatchObject({
      gramsPerUnit: "58.42",
      printMinutesPerUnit: 124,
    });
    expect(suggestFromPlate(p1, 3)).toMatchObject({
      gramsPerUnit: "19.48",
      printMinutesPerUnit: 42,
    });
  });

  it("refuses to suggest when the file lacks time or units are invalid", () => {
    const [noTime] = parseSliceInfo(NO_WEIGHT).plates;
    expect(suggestFromPlate(noTime, 1)).toEqual({
      ok: false,
      message: expect.stringContaining("no print-time estimate"),
    });
    expect(suggestFromPlate(p1, 0).ok).toBe(false);
    expect(suggestFromPlate(p1, 1.5).ok).toBe(false);
  });

  it("matches materials by type and colour, never across types", () => {
    const mats = [
      { id: "pla-black", typeCode: "PLA", colorHex: "#000000" },
      { id: "pla-white", typeCode: "PLA", colorHex: "#ffffff" },
      { id: "petg-red", typeCode: "PETG", colorHex: null },
    ];
    expect(matchMaterial(p1.filaments[0], mats)).toEqual({
      material: mats[0],
      exact: true,
    });
    expect(matchMaterial(p2.filaments[1], mats)).toEqual({
      material: mats[1],
      exact: true,
    });
    // Same type, no colour match, single candidate → suggested but not exact.
    expect(matchMaterial(parseSliceInfo(V104).plates[0].filaments[0], mats)).toEqual({ material: mats[2], exact: false });
    // Ambiguous (two PLAs, neither matching) → no suggestion.
    expect(matchMaterial({ ...p1.filaments[0], color: "#123456" }, mats)).toBeNull();
    expect(matchMaterial({ ...p1.filaments[0], type: "ASA" }, mats)).toBeNull();
  });
});

describe("readBambu3mf (archive level)", () => {
  it("reads a sliced archive with project settings and thumbnails", async () => {
    const file = await buildBambu3mf({
      sliceInfo: CURRENT,
      projectSettings: PROJECT,
      thumbnails: { 1: TINY_PNG, 2: new TextEncoder().encode("not a png") },
    });
    const res = await readBambu3mf(file, { thumbnails: true });
    if (!res.ok) throw new Error(res.message);
    expect(res.info.plates).toHaveLength(2);
    expect(res.project?.printerModel).toBe("Bambu Lab P1S");
    expect(Object.keys(res.thumbnails)).toEqual(["1"]); // the fake PNG is rejected
    expect(res.notes).toEqual([]);
  });

  it("accepts an ArrayBuffer and skips thumbnails unless asked", async () => {
    const file = await buildBambu3mf({
      sliceInfo: V104,
      thumbnails: { 1: TINY_PNG },
    });
    const res = await readBambu3mf(file.buffer.slice(file.byteOffset, file.byteOffset + file.byteLength) as ArrayBuffer);
    expect(res.ok && Object.keys(res.thumbnails)).toEqual([]);
  });

  it("explains each failure with a specific reason", async () => {
    expect(await readBambu3mf(new TextEncoder().encode("solid cube\nendsolid"))).toMatchObject({ ok: false, reason: "NOT_ZIP" });
    expect(await readBambu3mf(new Uint8Array([0x50, 0x4b, 3, 4, 0, 0]))).toMatchObject({ ok: false, reason: "NOT_ZIP" });
    expect(
      await readBambu3mf(
        await buildBambu3mf({
          contentTypes: false,
          extra: { "readme.txt": "hi" },
        }),
      ),
    ).toMatchObject({ ok: false, reason: "NOT_3MF" });
    expect(await readBambu3mf(await buildBambu3mf({}))).toMatchObject({
      ok: false,
      reason: "NO_SLICE_INFO",
    });
    expect(await readBambu3mf(await buildBambu3mf({ sliceInfo: UNSLICED }))).toMatchObject({
      ok: false,
      reason: "NOT_SLICED",
      clientVersion: "02.02.01.60",
      message: expect.stringContaining("Export plate sliced file"),
    });
    expect(await readBambu3mf(await buildBambu3mf({ sliceInfo: "<config><plate" }))).toMatchObject({ ok: false, reason: "MALFORMED" });
  });

  it("notes unreadable project settings but still returns the slice data", async () => {
    const res = await readBambu3mf(await buildBambu3mf({ sliceInfo: V104, projectSettings: "{not json" }));
    expect(res.ok && res.notes).toEqual(["Project settings could not be read; only slice results are shown."]);
  });

  it("refuses to inflate oversized metadata (zip-bomb guard)", async () => {
    const zip = new JSZip();
    zip.file("[Content_Types].xml", "<Types/>");
    // 5 MB of spaces compresses to a few KB but exceeds the 4 MB read cap.
    zip.file("Metadata/slice_info.config", `<config>${" ".repeat(5 * 1024 * 1024)}</config>`);
    const bomb = await zip.generateAsync({
      type: "uint8array",
      compression: "DEFLATE",
    });
    expect(bomb.length).toBeLessThan(100_000);
    expect(await readBambu3mf(bomb)).toMatchObject({
      ok: false,
      reason: "TOO_LARGE",
    });
  });

  it("finds entries case-insensitively, as the slicer does", async () => {
    const res = await readBambu3mf(await buildBambu3mf({ extra: { "metadata/Slice_Info.config": V104 } }));
    expect(res.ok).toBe(true);
  });
});
